---
- name: Copy jar file to inventory i.e. Pull docker image
  hosts: all
  tasks:
          - name: Install requests library
            pip:
                  name: requests
                  state: present
                  
                  
          - name: Pull junit devops image 
            docker_image:
                  name: amishraj/calculator 
                  source: pull
                  
            
                  
          - name: running container
            shell: docker run -it -d amishraj/calculator /bin/bash        
